version: "3.7"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.35
    restart: "no"
    environment:
      MYSQL_DATABASE: 'spring_angular'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: 'your_username'
      MYSQL_PASSWORD: 'your_password'
    ports:
      - '3306:3306'